name: Run build/tests/lint on pull requests

on:
  pull_request:
  push:

# By default the karma test runners use the karma 'Chrome' runner
# This is great when running locally because the browser pops up and you get to see what it does
# This doesn't work in Actions, however, so we set this env var to force the Headless runner
env:
  TEST_BROWSERS: ChromeHeadless

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false # continue testing on all platforms even if one fails
    steps:
      - uses: actions/checkout@v3
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm install
      - run: npm run build-test
      - name: Perform CodeQL Analysis
        if: matrix.os == 'ubuntu-latest' # we only need to run this check on one platform
        uses: github/codeql-action/analyze@v1
